### ISSUE TITLE
Source map no longer working correctly for Vega-Lite

### ISSUE THREAD

**Issue by kanitw** [vega/editor#95] opened 2018-05-28 02:19 UTC
(It might be related to the webpack upgrade?)

**Comment by domoritz** [comment] 2018-05-28 02:40
Or the rollup changes in Vega-Lite itself. I'm not sure whether rollup correctly maps the sourcemaps back to the ts files.

**Comment by domoritz** [comment] 2018-05-30 20:07
Duplicate of #4

**Closed by domoritz** 2018-05-30 20:07 UTC
