### ISSUE TITLE
Optionally post as gist to avoid really long urls

### ISSUE THREAD

**Issue by metasoarous** [vega/editor#174] opened 2018-10-25 07:10 UTC
I understand that the Vega Editor now stores the state of the visualization in the url using LZ compression. This is wonderful and brilliant!

![image](https://user-images.githubusercontent.com/88556/47481052-50558800-d7e7-11e8-9dcb-0d804a887f2e.png)

However, these can get quite long for more involved specs (of vega vs vega-lite especially)

![image](https://user-images.githubusercontent.com/88556/47481044-4895e380-d7e7-11e8-9c44-c5c5eea284c1.png)

I realize that it's easy enough to get around this by using the `[]()` markdwon syntax to get around this in GitHub issues, but (e.g.) I can't paste the above link as a tweet. Obviously it's not too hard to copy paste the body into a GitHub gist manually, like back in the dark long-ago, but it would be wonderful as a convenience if this could be done automatically from the app. Maybe when you click on the Gist button you see a "Save current viz as gist" link?

Thanks in advance

**Comment by domoritz** [comment] 2018-10-25 08:10
This is definitely the goal! 

You can already manually create a gist and load it like here: https://vega.github.io/editor/#/gist/vega-lite/domoritz/455e1c7872c4b38a58b90df0c3d7b1b9/96befdb6e155277a7c9d0521f24246784f3930d1/bar.vl.json

We will work on adding support for saving gist when we get to it. It's a high priority. 

Duplicate of #49.

**Closed by domoritz** 2018-10-25 08:10 UTC

**Comment by metasoarous** [comment] 2018-10-25 08:29
Wonderful; Thank you!
