### ISSUE TITLE
Cannot format spec

### ISSUE THREAD

**Issue by domoritz** [vega/editor#93] opened 2018-05-22 00:41 UTC
<img width="679" alt="screen shot 2018-05-21 at 15 59 00" src="https://user-images.githubusercontent.com/589034/40336401-3c36080c-5d1e-11e8-8b22-7c3de3d3e2b3.png">

**Comment by ydlamba** [comment] 2018-05-24 14:46
This can be fixed after https://github.com/Microsoft/monaco-editor/issues/889.

**Comment by ydlamba** [comment] 2018-06-23 22:02
It appears to be fixed now. So closing it.

**Comment by nesterone** [comment] 2018-07-31 15:53
Hi, @domoritz , @ydlamba 
Not sure that I can reproduce it
https://monosnap.com/file/smrRAg1eHNlCRt3a8zS2Eq4iLq1qEa

Is it still actual?

**Comment by domoritz** [comment] 2018-07-31 16:26
Definitely! Just press format multiple times. 

![editor](https://user-images.githubusercontent.com/589034/43472999-d18e456a-94a3-11e8-85ec-6bf699b11345.gif)

**Comment by nesterone** [comment] 2018-08-12 18:35
According to Microsoft/monaco-editor#889, it's about extending monaco api, so looks like I will create another PR to MS ;-)

**Comment by algomaster99** [comment] 2019-03-11 01:09
@domoritz What is the expected behaviour?

**Comment by domoritz** [comment] 2019-03-11 01:10
Format only according to prettier. Not switching between different formatters.

**Comment by algomaster99** [comment] 2019-03-11 04:22
One things we can do here is let the user in someway know which is the formatted code. Right now it just gets toggled and one cannot figure out which one is being rendered. Can be a a good UX feature. What do you say @domoritz ?

**Comment by algomaster99** [comment] 2019-03-11 05:00
@domoritz So format shouldn't toggle between code right? Once clicked and done.

**Comment by domoritz** [comment] 2019-08-02 11:11
Somehow we are not even calling our formatter in https://github.com/vega/editor/blob/0af13c747803e86648c02056d87a413995da340b/src/utils/monaco.ts#L53 anymore.

**Closed** 2019-09-19 19:29 UTC
Labels: bug, help wanted
