### ISSUE TITLE
vega editor crashes when running locally

### ISSUE THREAD

**Issue by unode** [vega/editor#715] opened 2020-06-10 23:50 UTC
Steps to reproduce:

1. `git clone git@github.com:vega/editor.git -b gh-pages` && `cd editor`
2. `python -m http.server`
3. Open http://0.0.0.0:8000/#/examples/vega/earthquakes in Chromium
4. In line `104` change `"type": "shape"` to `"type": "symbol"`

At this point the editor crashes (browser becomes a blank page) and shows the following errors in the JavaScript console.
```
logger.ts:102
TypeError: e.slice is not a function
    at t.a (parse.js:15)
    at symbols.js:148
    at f (symbols.js:141)
    at shapes.js:37
    at o (symbol.js:29)
    at _ (shapes.js:86)
    at Object.attr (markItemPath.js:13)
    at h.g._update (SVGRenderer.js:541)
    at h (SVGRenderer.js:343)
    at a (visit.js:35)
```
and
```
run.js:157 
Uncaught (in promise) Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=TypeError%3A%20e.slice%20is%20not%20a%20function&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at So (react-dom.production.min.js:139)
    at h (react-dom.production.min.js:143)
    at g (react-dom.production.min.js:145)
    at react-dom.production.min.js:149
    at Na (react-dom.production.min.js:173)
    at ms (react-dom.production.min.js:265)
    at cu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Js (react-dom.production.min.js:239)
    at react-dom.production.min.js:12
```

The same happens if I clone the `master` branch and use `yarn && yarn start`.

Is there a way around these errors? I'd like to use the editor locally with custom data.
Thanks

**Comment by domoritz** [comment] 2020-06-11 00:11
Can you follow the normal setup and run from master with yarn start?

**Comment by unode** [comment] 2020-06-11 00:55
> The same happens if I clone the `master` branch and use `yarn && yarn start`.

^ I tried that too and got the same beaviour.

**Comment by unode** [comment] 2020-06-11 01:01
And the corresponding errors
```
logger.ts:104
TypeError: pathstr.slice is not a function
    at parse.js:15
    at customSymbol (symbols.js:148)
    at symbols (symbols.js:141)
    at type (shapes.js:37)
    at symbol (symbol.js:29)
    at symbol (shapes.js:86)
    at Object.attr (markItemPath.js:13)
    at SVGRenderer.push../node_modules/vega-scenegraph/src/SVGRenderer.js.prototype._update (SVGRenderer.js:541)
    at process (SVGRenderer.js:343)
    at visit (visit.js:35)
```

```
react-dom.development.js:13413
Uncaught (in promise) Error: Objects are not valid as a React child (found: TypeError: pathstr.slice is not a function). If you meant to render a collection of children, use an array instead.
    in li (created by ErrorPane)
    in ul (created by ErrorPane)
    in div (created by ErrorPane)
    in ErrorPane (created by ConnectFunction)
    in ConnectFunction (created by VizPane)
    in div (created by VizPane)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by VizPane)
    in VizPane (created by ConnectFunction)
    in ConnectFunction (created by App)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(App)) (created by Context.Consumer)
    in Route (created by AppShell)
    in Switch (created by AppShell)
    in div (created by AppShell)
    in AppShell
    in Router (created by HashRouter)
    in HashRouter
    in Provider
    at throwOnInvalidObjectType (react-dom.development.js:13413)
    at createChild (react-dom.development.js:13651)
    at reconcileChildrenArray (react-dom.development.js:13900)
    at reconcileChildFibers (react-dom.development.js:14305)
    at reconcileChildren (react-dom.development.js:16762)
    at updateHostComponent (react-dom.development.js:17302)
    at beginWork (react-dom.development.js:18627)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
throwOnInvalidObjectType @ react-dom.development.js:13413
createChild @ react-dom.development.js:13651
reconcileChildrenArray @ react-dom.development.js:13900
reconcileChildFibers @ react-dom.development.js:14305
reconcileChildren @ react-dom.development.js:16762
updateHostComponent @ react-dom.development.js:17302
beginWork @ react-dom.development.js:18627
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
batchedUpdates$1 @ react-dom.development.js:21862
notify @ Subscription.js:19
notifyNestedSubs @ Subscription.js:92
handleChangeWrapper @ Subscription.js:97
dispatch @ redux.js:222
(anonymous) @ index.js:11
DispatchingLogger.error @ logger.ts:106
(anonymous) @ Dataflow.js:134
evaluate @ run.js:103
```

**Comment by domoritz** [comment] 2020-06-11 01:01
I can actually reproduce this in the online editor. Try what you said above and then click on the log panel.

**Comment by unode** [comment] 2020-06-11 01:06
Oh that's interesting. I was trying to reproduce it on the online editor but it was working fine.
After visiting the reset page it stopped working and now crashes the same.

**Comment by domoritz** [comment] 2020-06-11 01:14
Looks like the editor is not handling object correctly. I'm on it. 

<img width="255" alt="Screen Shot 2020-06-10 at 18 12 20" src="https://user-images.githubusercontent.com/589034/84333942-f7ff0580-ab45-11ea-8d9b-0dd8c1a7441b.png">

**Comment by unode** [comment] 2020-06-11 01:15
On the `gh-pages` branch, 498bb75836a17f1c458d26aacf109cd3c3958e6f is the most recent commit that works for me.

**Comment by domoritz** [comment] 2020-06-11 01:21
Fix released in 0.81.1 (deploying to production right now). Please give it a try in a few minutes.

**Closed** 2020-06-11 01:21 UTC
Labels: bug

**Comment by unode** [comment] 2020-06-11 01:38
Works for me online. `[Error] datum.properties is undefined`

However running locally from `master` I don't get the same message:
`[Error] pathstr.slice is not a function`
and from the `gh-pages` branch I see `[Error] e.slice is not a function` due to minification.

**Comment by domoritz** [comment] 2020-06-11 04:06
That's expected. I'm glad it's working now.
