### ISSUE TITLE
Setup instructions don't work on windows

### ISSUE THREAD

**Issue by abzachshan** [vega/editor#594] opened 2020-01-29 13:19 UTC
editor\src\constant\spec.ts requires 2 files:

export const VEGA_SPECS = require('../../public/spec/vega/index.json');
export const VEGA_LITE_SPECS = require('../../public/spec/vega-lite/index.json');

I followed the rather simple instructions in readme to start up the project but because both of the specs are non-existent in the project, it causes a compilation failure (See 1st image).

These files were deleted in a previous commit and I was able to get it started when I pulled them from the commit and put them in the correct folders - I imagine this is not how it is supposed to be and there's a reason for their removal.

There's a problem using the docker-compose as-well (See 2nd image). I don't know if the cause is the same.

Would love to get some help.

![Untitled](https://user-images.githubusercontent.com/16580199/73359822-5a97e900-42aa-11ea-984d-049993e9b6fd.png)

![Untitled1](https://user-images.githubusercontent.com/16580199/73361758-42c26400-42ae-11ea-977f-bfcbc5df1550.png)

**Comment by domoritz** [comment] 2020-01-29 18:58
I don't have a windows machine and it looks like the instructions don't work there. Can you help fix it?

**Comment by IamRavikantSingh** [comment] 2020-01-30 08:49
I had the same issue on mac as in your first image your specs folder would be empty.
In my case, the issue was with `wget`. After installing wget everything worked.

**Comment by abzachshan** [comment] 2020-01-30 19:12
Hey @domoritz and @IamRavikantSingh, I was able to narrow down the problem - the scripts that are used (located in 'editor/scripts') when you run the yarn command, are heavily reliant on Linux OS commands which are non-existent on Windows OS (such as wget, rsync, tar). 

I'll try working on a generic solution whenever I can

**Comment by domoritz** [comment] 2020-01-30 19:39
I see. Rather than making the script work on windows, let's just have people use docker instead and make sure docker works, okay?

**Comment by abzachshan** [comment] 2020-01-30 20:08
Sure. I believe fixing the docker and publishing the dockerized image would be a great idea! I was also hoping there would be one when we first tried to set this up

**Comment by domoritz** [comment] 2020-01-30 23:06
I don't think we need to publish an image. Just make the setup we have work.

**Comment by baumanab** [comment] 2020-02-05 06:03
This is mostly in reference to the dockerfile..Based on my experiments it looks like the issue is the line endings on 'vendor.sh' and 'version.sh' when cloning into windows.  The current sed lines are not fixing this for some reason, even after I apply them to both files.  If I remove lines after `copy ..` in the docker file, run the container, and convert crlf to lf (using vim) and then run `yarn` and `yarn start` everything works.  I'm working out a more elegant solution.

**Comment by abzachshan** [comment] 2020-02-05 06:49
@baumanab I have a pull request fixing the dockerfile and cleaning it a bit - I’d  appreciate if you could take a look

**Comment by baumanab** [comment] 2020-02-05 07:10
I didn't find a more elegant solution.  Here is something that works though.  

```
docker build -t vle .
```

If you are on window it's safest to run this next one in powershell due to the mount

```
docker run -dit -p 8080:8080 -v ${PWD}/src:/usr/src/app/src vle
```

I made some changes to the dockerfile.  

```
FROM node:latest

# Fetch updated list of packages and upgrade operating system for next step (install rsync)
RUN apt-get update && apt-get upgrade -y && \
    apt-get -y install rsync \
      dos2unix \
&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
    && rm -rf /var/lib/apt/lists/*

# Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow it in the Dockerfile
# https://docs.docker.com/engine/reference/builder/#workdir
WORKDIR /usr/src/app

# Copies the package.json and yarn.lock files first to ensure the cache is only invalidated when these files change
# https://nodejs.org/en/docs/guides/nodeodejs-docker-webapp/#creating-a-dockerfile
COPY package.json yarn.lock ./

# For this project, additional files must also be copied as yarn hooks depend on them
COPY scripts ./scripts

# Copy remaining files
COPY . .

# Remove 'r' characters from the vendor script (otherwise it won't execute)
RUN dos2unix ./scripts/vendor.sh && \
    dos2unix ./scripts/version.sh 

# Run Yarn
RUN yarn

# Sets the container executable (ENTRYPOINT) as yarn and the default argument (CMD) as start
# https://docs.docker.com/engine/reference/builder/#entrypoint
# https://docs.docker.com/engine/reference/builder/#cmd
ENTRYPOINT ["yarn"]
CMD ["start"]
```

**Comment by baumanab** [comment] 2020-02-05 07:11
> @baumanab I have a pull request fixing the dockerfile and cleaning it a bit - I’d appreciate if you could take a look

I didn't see your message before my post.  I'll try it out.  If there is any interest in the Dockerfile I used, I can put in a PR as well.

**Comment by baumanab** [comment] 2020-02-05 07:50
it works, leaving comments in the PR

**Comment by domoritz** [comment] 2020-02-11 22:47
Fixed in master. Use docker.

**Closed by domoritz** 2020-02-11 22:47 UTC
Labels: dev, help wanted
