### ISSUE TITLE
Make Vega Editor to understand simplified JSON

### ISSUE THREAD

**Issue by alexeypetrushin** [vega/editor#569] opened 2019-12-16 10:16 UTC
The Editor https://vega.github.io/editor/#/edited
Requires you to write strict JSON with all literal wrapped in double quotes, like `{ "value": "something" }`.

It fails on simplified JSON `{ value: "something" }` or `{ "value": 'something' }`.

The whole point of this editor is to provide simple and easy environment to play with Vega charts, would be much better to allow easy JSON instead of requiring strict JSON.

**Comment by domoritz** [comment] 2019-12-16 19:43
Duplicate of https://github.com/vega/editor/issues/171. 

To convert simple JSON/JS to JSON, you can use http://bit.ly/js2json.

**Closed by domoritz** 2019-12-16 19:43 UTC

**Comment by alexeypetrushin** [comment] 2019-12-17 09:25
Of course I can convert, I don't even use that editor and use my own IDE with live graph view and update. That's not my point. 

The point was that if you care about promotion of VegaLite and want more people to use it - it's worth to make the experience nice and pleasant.

**Comment by domoritz** [comment] 2019-12-17 16:48
I completely agree but there are technical and pedagogical reasons why we haven’t added support for other formats.
