### ISSUE TITLE
Error message feedback.

### ISSUE THREAD

**Issue by theWebalyst** [vega/editor#643] opened 2020-03-16 17:02 UTC
I've been asked to say a little about how the Vega editor could improve its error feedback. I don't have any great insights, but found that it was much easier for me to understand what I was doing wrong with the feedback from VS Code (actually VSCodium) Vega Preview.

The main difference is that the errors in Vega Preview are highlighted in the editor itself, and hovering over them gives quite specific and helpful feedback (things like what type was expected). Whereas Vega editor logs are often a long list of very similar messages which were hard for me to relate to the relevant line or character in the edit window.

Here's an example, actually one of the more helpful from the Vega editor logs. Here it points to the location of an error, but for me that was often not the case and I just had the list of messages that probably help if you are familiar with Vega, but not so much for someone new:
<img width="674" alt="Screen Shot 2020-03-16 at 09 51 47" src="https://user-images.githubusercontent.com/2183895/76782106-ad205c80-67a7-11ea-81ae-ff19d493f5bd.png">

**Comment by domoritz** [comment] 2020-03-16 17:23
Note that the Vega Editor shows error messages in the editor and provides suggestions in the tooltip. 

<img width="726" alt="Screen Shot 2020-03-16 at 09 51 41" src="https://user-images.githubusercontent.com/589034/76783988-22703b00-6770-11ea-98ac-231dc3d7e523.png">

**Comment by domoritz** [comment] 2020-03-16 17:25
Duplicate of https://github.com/vega/editor/issues/3

**Closed by domoritz** 2020-03-16 17:25 UTC
