### ISSUE TITLE
energy warning of browser using editor

### ISSUE THREAD

**Issue by mattijn** [vega/editor#144] opened 2018-07-27 09:37 UTC
While working with the updated editor I oftenly get warnings and errors related to energy usage and memory overload of the browser. 

I hear the fan going wild and when closing the editor it goes backs to normal.

<img width="620" alt="energy" src="https://user-images.githubusercontent.com/5186265/43313680-15bc5738-9191-11e8-8749-9c0460d4b6c8.png">

**Comment by domoritz** [comment] 2018-07-27 15:15
Hmm, odd. I've had no problems in Firefox and chrome. Does this just happen in safari?

**Comment by domoritz** [comment] 2019-07-29 09:45
That's an amazing example. Not sure whether it's really the typical example for the editor.

![editor](https://user-images.githubusercontent.com/589034/62038490-19892400-b1f6-11e9-80a5-0a713aba836b.gif)

In static examples, the editor doesn't use a lot of CPU.

**Comment by domoritz** [comment] 2020-04-29 18:39
Closing since I think the issue is due to the complex visualization, not the editor.

**Closed by domoritz** 2020-04-29 18:39 UTC
Labels: bug
