### ISSUE TITLE
Mouse wheel does not scroll editor in Firefox

### ISSUE THREAD

**Issue by MakoSDV** [vega/editor#353] opened 2019-05-23 19:22 UTC
In Firefox, using the mouse wheel (or touchpad scroll gesture) does not scroll the left-side JSON Editor div like it does in Chrome.

To reproduce using Firefox, open the Bar Chart example in Vega editor and switch it to Vega mode (this will likely overflow and enable the vertical scroll bar).  When using the mouse wheel, nothing happens.  In order to scroll, you must drag the scroll bar or move the cursor with the up/down keys.

Tested in Firefox 67.

**Comment by domoritz** [comment] 2019-05-23 20:08
Something must be highjacking the scroll event. Thanks for the report.

**Comment by siddhant1** [comment] 2019-05-24 07:08
Will check!

**Comment by siddhant1** [comment] 2019-05-24 15:10
Looked on it for a while , here are my findings.
This is not the issue with us , the issue is prevailing in the monaco-editor , see issue (https://github.com/Microsoft/monaco-editor/issues/1353)

Also there is a corresponding pull request (https://github.com/microsoft/vscode/pull/72832) while resolves this issue but is not merged yet.

This is happening because the firefox does not recognize the `mousewheel` event , rather it supports `DOMMouseScroll` event , the pr (https://github.com/microsoft/vscode/pull/70515) resolves the issue completely by using `wheel` event.

Currently we can do cntrl + up/down to scroll in firefox  but we have to manually patch monaco-editor in the node_modules and add the fix , if the browser.window = firfox) we can register the event named DOMMouseScroll.

@domoritz So , should I make changes in the node_modules or should can we work around with this one?

**Comment by domoritz** [comment] 2019-05-24 18:03
Let’s wait for Monaco to fix this then. One issue for us is that we had trouble updating Monaco. Can you try to update it so we are on the latest version? Thanks!

**Comment by siddhant1** [comment] 2019-05-24 18:46
Sure!

**Comment by siddhant1** [comment] 2019-07-28 07:56
https://github.com/microsoft/monaco-editor/issues/1353#issuecomment-515222615

**Closed** 2019-07-28 08:25 UTC
Labels: bug, help wanted
