### ISSUE TITLE
Bug : Can't go back from edit vega

### ISSUE THREAD

**Issue by siddhant1** [vega/editor#246] opened 2019-03-09 14:49 UTC
Once you click on edit Vega Spec  , the editor shows the vega spec , Now you cannot go back to vega-lite spec again.
If you change to vega-lite in upper drawer , it shows a single line,
Now again switch to vega , It will again show a single line.
Investigating!

**Comment by domoritz** [comment] 2019-03-09 14:57
Duplicate of #12.

**Closed by domoritz** 2019-03-09 14:57 UTC
