### ISSUE TITLE
>     TS2741: Property 'error' is missing in type 'LocalLogger' but required in type 'LoggerInterface'.

### ISSUE THREAD

**Issue by kanitw** [vega/editor#308] opened 2019-03-23 04:17 UTC
>     TS2741: Property 'error' is missing in type 'LocalLogger' but required in type 'LoggerInterface'.

**Comment by domoritz** [comment] 2019-03-23 14:26
Duplicate of https://github.com/vega/editor/issues/307

**Closed by domoritz** 2019-03-23 14:26 UTC
